---
title: "Final Project: Multi-Dimensional Analysis of Survey Data"
author: "Porter Bischoff"
output:
  html_document:
    toc: true
    toc_float: true
    theme:
      bootswatch: solar
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **What is the data?**

This data is survey data collected at Utah Valley University in the Spring and Fall 2020 semesters. The survey explores different aspects of science motivation, with a goal of understanding what things may have an effect on a student's science motivation. The questions were adapted from other surveys found in the literature review conducted. These are the different aspects of science motivation that we explored:
<br>

### Science Identity

Questions regarding "Science Identity" included:
<br>

  <ul>
    <li>"I see myself as a biology person"</li>
    <li>"I see myself as a science person"</li>
    <li>"I see myself as a scientist"</li>
    <li>"Other people (friends/family) see me as a science person"</li>
    <li>"My science instructors see me as a science person"</li>
  </ul>

### Career Motivation

Questions regarding "Career Motivation" included:
<br>

  <ul>
    <li>"Learning science will help me get a good job"</li>
    <li>"Understanding science will benefit me in my career"</li>
    <li>"Knowing science will give me a career advantage"</li>
    <li>"I will use science problem-solving skills in my career"</li>
    <li>"My career will involve science"</li>
  </ul>
### Intrinsic Motivation

Questions regarding "Intrinsic Motivation" included:
<br>

  <ul>
    <li>"Learning science is interesting"</li>
    <li>"I am curious about discoveries in science"</li>
    <li>"The science I learn is relevant to my life"</li>
    <li>"Learning science makes my life more meaningful"</li>
    <li>"I enjoy learning science"</li>
  </ul>
### Self-Determination

Questions regarding "Self-Determination" included:
<br>

  <ul>
    <li>"I study hard to learn science"</li>
    <li>"I prepare well for science tests and labs"</li>
    <li>"I put enough effort into learning science"</li>
    <li>"I spend a lot of time learning science"</li>
    <li>"I use strategies to learn science well"</li>
  </ul>
### Self-Efficacy 

Questions regarding "Self-Efficacy" included:
<br>

  <ul>
    <li>"I am confident I will do well on science labs and projects"</li>
    <li>"I believe I can earn a grade of 'A' in science"</li>
    <li>"I am confident I will do well on science tests"</li>
    <li>"I believe I can master science knowledge and skills"</li>
    <li>"I am sure I can understand science"</li>
  </ul>
### Grade Motivation

Questions regarding "Grade Motivation" included:
<br>

  <ul>
    <li>"Scoring high on science tests and labs matters to me"</li>
    <li>"It is important that I get an 'A' in science"</li>
    <li>"I think about the grade I will get in science"</li>
    <li>"Getting a good science grade is important to me"</li>
    <li>"I like to do better than other students on science tests"</li>
  </ul>
### Science Competency 

Questions regarding "Science Competency" included:
<br>

  <ul>
    <li>"I am good at solving complicated scientific problems"</li>
    <li>"I read websites, articles, or books about scientific issues"</li>
    <li>"I work on a project involving scientific concepts"</li>
    <li>"I think about how mu life is affected by science"</li>
  </ul>
### Personal Community Orientation 

Questions regarding "Personal Community Orientation" included:
<br>

  <ul>
    <li>"To what extent is serving your community important to you?"</li>
    <li>"To what extent is working with people important to you?"</li>
    <li>"To what extent is helping others important to you?"</li>
    <li>"To what extent is connecting with others important to you?"</li>
  </ul>
  
These questions were given choices from "Not important at all" to "Extremely important" as answer choices. 
<br>

### Science Community Orientation

Questions regarding "Science Community Orientation" included:
<br>

  <ul>
    <li>"To what extent is serving your community important to scientific work?"</li>
    <li>"To what extent is working with people important to scientific work?"</li>
    <li>"To what extent is helping others important to scientific work?"</li>
    <li>"To what extent is connecting with others important to scientific work?"</li>
  </ul>

These questions were given choices from "Not important at all" to "Extremely important" as answer choices. 
<br>

## **What is MDS?**

## **Demographics**

### *Major*

### *Gender*

### *Career Goals*

### *Ethnicity*

### *First Destination Students*

### *Number of Dependents*

### *Do you have a medical condition?*

### *Do you care for someone who has a medical condition?*

## **Conclusion**
